defaults: &defaults  
  title: Traffic Game
  session_secret: <%= ENV['ATT_HACK_SESSION_SECRET'] %>
  mapquest_api_key: <%= ENV['ATT_HACK_MAPQUEST_KEY'] %>
development:  
  <<: *defaults

test:  
  <<: *defaults

staging:  
  <<: *defaults

production:  
  <<: *defaults